### ISSUE TITLE
Exit code is not 0 when lab fails

### ISSUE THREAD

**Issue by juancri** [otodockal/gulp-lab#12]
When lab is running on bash and a test fails, the exit code is 1.

When running the same suite with gulp-lab, the exit code is 0.

This is similar to this problem:
http://stackoverflow.com/questions/21688613/gulp-returns-0-when-tasks-fail

Is there any callback to get the real lab exit code? Thank you!

**Comment by otodockal** [comment]
When lab returns exit code 1, gulp-lab is able to report Error message. Check out this line https://github.com/otodockal/gulp-lab/blob/master/index.js#L91

But you have to set explicitly prop emitLabError to true. More here:
https://github.com/otodockal/gulp-lab#example-4---options-by-an-object-in-conjunction-with-jshint

Is it enough or not? I can change it, let me know. Btw. sorry for the late response!

**Comment by juancri** [comment]
I just saw this! I think that could work. Thanks!
