### ISSUE TITLE
hapi based lab now called @hapi/lab

### ISSUE THREAD

**Issue by tdukai** [otodockal/gulp-lab#14]
// We expect that lab was declared as a project dependencies, and run directly its main script
  // this way, it can be executed on every platform.
  var args = [Join(process.cwd(), 'node_modules', '@hapi/lab', 'bin', 'lab')];

**Comment by alelapi** [comment]
Same problem. I opened a PR to fix it
#15

**Comment by otodockal** [comment]
Thank you and sorry for the delay, will release a new version today.

**Comment by otodockal** [comment]
@tdukai @alelapi I've just released version 2.0.0. @hapi/lab is supported. Deprecated "lab" is supported in version 1.0.8.

Thank you for PR and patience.
